### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Jqw0623** [NothinX/StockTradingSystem#2]
不能运行

**Comment by Voimulax** [comment]
> 不能运行

运行需要新建一个数据库，默认给的是sql server的连接字符串
建库的sql是sql文件夹下的dbo.sql，然后afterdbo.sql提供一些初始数据
剩下其他的sql文件是触发器和存储过程

不建议使用本系统，没啥价值。。

**Comment by Jqw0623** [comment]
哈哈，我说的是wpf部分会在第一界面崩溃掉，我研究了下，没能修改好，
没搞懂

**Comment by Voimulax** [comment]
> 哈哈，我说的是wpf部分会在第一界面崩溃掉，我研究了下，没能修改好，
> 没搞懂

那还是别搞懂它了，没啥意义，浪费你的时间

**Comment by henuliulei** [comment]
全部功能都实现了啊！写的真的挺棒的，咋会没意义呢？大佬

**Comment by Voimulax** [comment]
> 全部功能都实现了啊！写的真的挺棒的，咋会没意义呢？大佬

😂

**Comment by henuliulei** [comment]
学长你们创新实践老师是崔翔吗

**Comment by Voimulax** [comment]
> 全部功能都实现了啊！写的真的挺棒的，咋会没意义呢？大佬

你是谁？不要在这里和我聊天，有事qq找我

**Comment by henuliulei** [comment]
你学弟，没你的qq,。。。

**Comment by Voimulax** [comment]
> 全部功能都实现了啊！写的真的挺棒的，咋会没意义呢？大佬

我的邮箱是voimulax@qq.com，你把你qq号发给我
